# Keep in sync with DuyDM-PC.kdl output names.
wallpapers=(
    "eDP-1|$HOME/Pictures/wallpapers/natra1.jpg"
    "DP-3|$HOME/Pictures/wallpapers/natra3.jpg"
    "DP-4|$HOME/Pictures/wallpapers/natra2.jpg"
)
