# Keep in sync with DuyDM-PC.kdl output names.
wallpapers=(
    "eDP-1|$HOME/Pictures/wallpapers/natra1.jpg"
    "DP-1-8|$HOME/Pictures/wallpapers/natra3.jpg"
    "DP-1-9|$HOME/Pictures/wallpapers/natra2.jpg"
)
