[module/cpu]
type = internal/cpu
interval = 2
exec = eww open bar
#format-prefix            = ""
format-prefix-foreground	= ${colors.magenta}		
format-padding    = 2
label                    = "%{F#a9b1d6} %{F-}%{F#a9b1d6}%percentage:2%%%{F-}"
click-left	= eww open bar
