[module/date]
type = internal/date
interval = 1

format                = <label>
format-foreground     = ${colors.foreground}
#format-background	= #ffffff
#format-radius	= 0.9
format-background     = ${colors.darbk1}
format-prefix-foreground = ${colors.magenta}
format-prefix-padding = 1
label                 = %time%
label-foreground = ${colors.fg}
label-padding         = 1
radius	      = 9.0
time                  = %d/%m, %H:%M
time-alt              = %A, %d %B %Y

