[colors]
;background = ${xrdb:color0:#222}
background = #27374D
background-alt = #1a1b26
;foreground = ${xrdb:color7:#222}
foreground = #eceff4
foreground-alt = #ese9f0
primary = #7aa7f7
secondary = #e60053
alert = #bd2c40

bg = #181825
bg-alt = #1a1b26
fg = #ECEFF4
fg-alt = #E5E9F0

blue = #7aa2f7
cyan = #88C0D0
green = #A3BE8C
orange = #D08770
purple = #B48EAD
red = #BF616A
magenta = #ad8ee6
yellow = #EBCB8B

black = #000
white = #FFF

trans = #00000000
semi-trans-black = #aa000000

color1          = #b48ead
color2          = #ebcb8b
color3          = #81a1c1
color4          = #a3be8c
color5          = #9bf6ff
color6          = #ffd6a5
color7          = #bf616a
color8          = #bdb2ff
color9          = #caffbf

bcolor1         = #2e2e40 
bcolor2         = #313244
bcolor3         = #262633 
bcolor4         = #1e1e2e 
bcolor5         = #181825
bcolor6         = #11111b 

altblack = #444b6a
altred = #ff7a93
altgreen = #b9f27c
altyellow = #ff9e64
altblue = #7aa2f7
altmagenta = #bb9af7
altcyan = #0db9d7
altwhite = #acb0d0

blue1 = #7aa2f7
blue2 = #4E83C9
blue3 = #4170ba
blue4 = #2871cc
blue5 = #003f9a

darkb1 = #23395d
darkb2 = #203354
darkb3 = #1c2e4a
darkb4 = #192841
darkb5 = #152238

; background = #1a1b26
; background-alt = #24283b
; foreground = #c0caf5
; primary = #e0af68
; secondary = #9ece6a
; alert = #db4b4b
; disabled = #414868
; blue = #7aa2f7
bar1 = #27374D
bar2 = #526D82
bar3 = #9DB2BF