[colors]
; Bộ màu tím cho màn hình 2
background = #4a148c
background-alt = #24283b
foreground = #f3e5f5
fg = #f3e5f5
primary = #ffb74d
secondary = #81c784
alert = #e57373
disabled = #414868
blue = #9575cd  
bar1 = #7b1fa2
bar2 = #8e24aa
bar3 = #9c27b0
bar4 = #ab47bc
bar5 = #ba68c8
bar6 = #ce93d8
