; ===========================================
; CONFIG CHO MÀN HÌNH 1 (Màu hoàng hôn)
; ===========================================

[colors]
background = #2a1810
background-alt = #3d2415
foreground = #f5deb3
fg = #f5deb3
primary = #ff8c42
secondary = #ffb366
alert = #d94f3d
disabled = #5a4033
blue = #e07a5f
bg = #2a1810
green = #a3be8c
yellow = #ffd699
orange = #ff8c42
magenta = #d3869b
bar1 = #d96846
bar2 = #e07a5f
bar3 = #ff8c42
bar4 = #ffa866
bar5 = #ffb366
bar6 = #ffd699

include-file = ~/.config/polybar/modules.ini 
include-file = ~/.config/polybar/gylphs.ini

[bar/main]
monitor = ${env:MONITOR:}
wm-restack = bspwm
width = 1914
height = 30
radius = 6
fixed-center = true
dpi = 96
offset-x = 3pt
offset-y = 3pt
top = true
enable-ipc = true

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt
padding-left = 0
padding-right = 0

border-left-size = 0
border-right-size = 0
border-top-size = 0
border-bottom-size = 0
border-radius = 6

; Load fonts
include-file = ~/.config/polybar/fonts.ini

modules-left = left4 xworkspaces right4 rofi
modules-center = spotify
modules-right = cpu memory left1 date left2 battery bluetooth network pulseaudio right2 powermenu

scroll-up = next
scroll-down = prev

cursor-click = pointer
cursor-scroll = ns-resize

[module/xwindow]
type = internal/xwindow
label = %title%

[settings]
screenchange-reload = true
pseudo-transparency = true

[global/wm]
margin-top = 5
margin-bottom = 5
