; ===========================================
; CONFIG CHO MÀN HÌNH 2 (Màu tím)
; ===========================================

[colors]
background = #0d47a1
background-alt = #24283b
foreground = #e3f2fd
fg = #e3f2fd
primary = #e0af68
secondary = #9ece6a
alert = #db4b4b
disabled = #414868
blue = #7aa2f7  
bg = #0d47a1
green = #9ece6a
yellow = #e0af68
orange = #ff9e64
magenta = #bb9af7
bar1 = #1e88e5
bar2 = #2196f3
bar3 = #42a5f5
bar4 = #64b5f6
bar5 = #90caf9
bar6 = #bbdefb

include-file = ~/.config/polybar/modules.ini 
include-file = ~/.config/polybar/gylphs.ini

[bar/main]
monitor = ${env:MONITOR:}
wm-restack = bspwm
width = 1914
height = 30
radius = 6
fixed-center = true
dpi = 96
offset-x = 3pt
offset-y = 3pt
top = true
enable-ipc = true

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt
padding-left = 0
padding-right = 0

border-left-size = 0
border-right-size = 0
border-top-size = 0
border-bottom-size = 0
border-radius = 6

; Load fonts
include-file = ~/.config/polybar/fonts.ini

modules-left = left4 xworkspaces right4 rofi
modules-center = spotify
modules-right = cpu memory left1 date left2 battery bluetooth network pulseaudio right2 powermenu

scroll-up = next
scroll-down = prev

cursor-click = pointer
cursor-scroll = ns-resize

[module/xwindow]
type = internal/xwindow
label = %title%

[settings]
screenchange-reload = true
pseudo-transparency = true

[global/wm]
margin-top = 5
margin-bottom = 5
