; ===========================================
; CONFIG CHO MÀN HÌNH 3 (Màu đỏ-cam)
; ===========================================

[colors]
background = #b71c1c
background-alt = #24283b
foreground = #fff3e0
fg = #fff3e0
primary = #ff6f00
secondary = #ffa726
alert = #ffeb3b
disabled = #414868
blue = #ff9800  
bg = #b71c1c
green = #81c784
yellow = #ffeb3b
orange = #ff9800
magenta = #ce93d8
bar1 = #d84315
bar2 = #e64a19
bar3 = #ff5722
bar4 = #ff7043
bar5 = #ff8a65
bar6 = #ffab91

include-file = ~/.config/polybar/modules.ini 
include-file = ~/.config/polybar/gylphs.ini

[bar/main]
monitor = ${env:MONITOR:}
wm-restack = bspwm
width = 1914
height = 30
radius = 6
fixed-center = true
dpi = 96
offset-x = 3pt
offset-y = 3pt
top = true
enable-ipc = true

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt
padding-left = 0
padding-right = 0

border-left-size = 0
border-right-size = 0
border-top-size = 0
border-bottom-size = 0
border-radius = 6

; Load fonts
include-file = ~/.config/polybar/fonts.ini

modules-left = left4 xworkspaces right4 rofi
modules-center = spotify
modules-right = cpu memory left1 date left2 battery bluetooth network pulseaudio right2 powermenu

scroll-up = next
scroll-down = prev

cursor-click = pointer
cursor-scroll = ns-resize

[module/xwindow]
type = internal/xwindow
label = %title%

[settings]
screenchange-reload = true
pseudo-transparency = true

[global/wm]
margin-top = 5
margin-bottom = 5
